name: "cache"
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * *"

jobs:
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: locked (Linux)
          os: ubuntu-latest
        - name: nixos-22.11 (Linux)
          channel: nixos-22.11
          os: ubuntu-latest
        - name: nixpkgs-unstable (Linux)
          channel: nixpkgs-unstable
          os: ubuntu-latest
    name: nix-build
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: hmenke
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: "(-source$|nixpkgs.tar.gz$)"
    - name: Run nix-build
      run: |
        rev="$(git ls-remote https://github.com/NixOS/nixpkgs refs/heads/$channel | awk '{print $1}')"
        nixpkgs="fetchTarball \"https://github.com/NixOS/nixpkgs/archive/$rev.tar.gz\""
        nix-build \
            --show-trace \
            --option allow-import-from-derivation false \
            ${channel:+--arg pkgs "import ($nixpkgs) {}"}
      env:
        channel: '${{ matrix.channel }}'
  nix-flakes:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: locked (Linux)
          os: ubuntu-latest
        - name: nixos-22.11 (Linux)
          channel: nixos-22.11
          os: ubuntu-latest
        - name: nixpkgs-unstable (Linux)
          channel: nixpkgs-unstable
          os: ubuntu-latest
    name: nix flake check
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: hmenke
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: "(-source$|nixpkgs.tar.gz$)"
    - name: Run nix flake check
      run: |
        nix flake check \
            --print-build-logs \
            --show-trace \
            --option allow-import-from-derivation false \
            --option pure-eval true \
            ${channel:+--override-input nixpkgs github:NixOS/nixpkgs/$channel}
        nix flake archive --json ${channel:+--override-input nixpkgs github:NixOS/nixpkgs/$channel} |
            jq -r '.inputs[].path' |
            xargs nix-store --delete
      env:
        channel: '${{ matrix.channel }}'
